// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DropDown: typeof import('./src/components/Header/DropDown.vue')['default']
    DropDownItem: typeof import('./src/components/Header/DropDownItem.vue')['default']
    GlobalFooter: typeof import('./src/components/Footer/GlobalFooter.vue')['default']
    GlobalHeader: typeof import('./src/components/Header/GlobalHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loader: typeof import('./src/components/Loading/Loader.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
